---
- name: Generate CA for Self Signed Certs
  hosts: zookeeper[0]
  gather_facts: no
  tags: certificate_authority
  tasks:
  - import_role:
      name: confluent.variables_handlers
  - name: Create Certificate Authority and Copy to Ansible Host
    include_tasks: tasks/certificate_authority.yml
    when:
      - self_signed|bool
      - regenerate_ca|bool
      - ssl_enabled|bool

- name: Host Prerequisites
  hosts: zookeeper:kafka_broker
  tags: common
  environment: "{{ proxy_env }}"
  tasks:
  - import_role:
      name: confluent.common

- name: Zookeeper Provisioning
  hosts: zookeeper
  tags: zookeeper
  environment: "{{ proxy_env }}"
  tasks:
  - import_role:
      name: confluent.zookeeper

- name: Kafka Broker Provisioning
  hosts: kafka_broker
  tags: kafka_broker
  environment: "{{ proxy_env }}"
  tasks:
  - import_role:
      name: confluent.kafka_broker

- name: Schema Registry Provisioning
  hosts: schema_registry
  tags: schema_registry
  environment: "{{ proxy_env }}"
  tasks:
  - import_role:
      name: confluent.schema_registry


#- name: KSQL Provisioning
#  hosts: ksql
#  tags: ksql
#  environment: "{{ proxy_env }}"
#  tasks:
#  - import_role:
#      name: confluent.ksql
#
#- name: Control Center Provisioning
#  hosts: control_center
#  tags: control_center
#  environment: "{{ proxy_env }}"
#  tasks:
#  - import_role:
#      name: confluent.control_center
